api_version = "2025-10"

[[extensions]]
name = "typ-osp-survey"
handle = "typ-osp-survey"
type = "ui_extension"
uid = "4e3e11dc-1fe2-8e29-485c-901abf804ea06596c846"
[[extensions.targeting]]
module = "./src/ThankYouPageSurvey.jsx"
target = "purchase.thank-you.block.render"

